Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======

======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
Traceback (most recent call last):
  File "/Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py", line 82, in <module>
    for z in reange (0,8):
NameError: name 'reange' is not defined
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
Traceback (most recent call last):
  File "/Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py", line 82, in <module>
    for z in reange (0,8):
NameError: name 'reange' is not defined
>>> 
======== RESTART: /Users/mu.ssi/Desktop/TASKS TO DO👌🏻/BE/PYTHON/pizza.py =======
>>> 